version: "3.8"

services:
  goodmood-db:
    restart: unless-stopped
    container_name: goodmood-db
    image: postgis/postgis:14-3.3
    env_file:
      - config/db.env
    volumes:
      - goodmood-db-volume:/var/lib/postgresql/data
    networks:
      - goodmood-net

  goodmood-app:
    restart: unless-stopped
    container_name: goodmood-app
    depends_on:
      - goodmood-db
    image: goodmood:v1
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PRODUCTION=True
    volumes:
      - ./:/srv/goodmood
      - /etc/localtime:/etc/localtime
      - goodmood-static-volume:/srv/static
      - goodmood-media-volume:/srv/media
    networks:
      - goodmood-net

  goodmood-nginx:
    container_name: goodmood-nginx
    restart: unless-stopped
    image: nginx:v1
    build:
      context: ./config/nginx
      dockerfile: Dockerfile
    extra_hosts:
      - "extrahost:89.42.209.30"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./config/nginx/brotli.conf:/etc/nginx/conf.d/brotli.conf
      - goodmood-static-volume:/srv/static
      - goodmood-media-volume:/srv/media
      - /etc/letsencrypt/:/etc/letsencrypt/
    depends_on:
      - goodmood-app
    networks:
      - goodmood-net

networks:
  goodmood-net:
    name: goodmood-net

volumes:
  goodmood-db-volume:
  goodmood-static-volume:
  goodmood-media-volume:
